version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: my_database
    restart: always
    environment:
      POSTGRES_USER: your_postgres_username
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge